[
phases.setup
]
nixPkgs = ["jdk17"]

[
phases.build
]
cmds = ["cd demo && chmod +x gradlew && ./gradlew bootJar --no-daemon -x test"]

[
start
]
cmd = "java -jar demo/build/libs/demo-0.0.1-SNAPSHOT.jar"
